/** PM2 process file — adjust `cwd` to your machine path */
module.exports = {
  apps: [
    {
      name: "trading-bot",
      script: "/Users/fatman/.bun/bin/bun",
      args: "dist/index.js",
      cwd: __dirname,
      interpreter: "none",
      env_file: ".env",
      autorestart: true,
      max_restarts: 50,
      min_uptime: "10s",
    },
    {
      name: "evening-analyst",
      script: "/Users/fatman/.bun/bin/bun",
      args: "dist/analyst.js",
      cwd: __dirname,
      interpreter: "none",
      env_file: ".env",
      autorestart: false,
      cron_restart: "45 15 * * 1-5",
      timezone: "Asia/Kolkata",
    },
    {
      name: "evening-live-analyze",
      script: "/Users/fatman/.bun/bin/bun",
      args: "dist/live-analyze.js",
      cwd: __dirname,
      interpreter: "none",
      env_file: ".env",
      autorestart: false,
      cron_restart: "35 15 * * 1-5",
      timezone: "Asia/Kolkata",
    },
    {
      name: "nightly-discovery",
      script: "/Users/fatman/.bun/bin/bun",
      args: "dist/discovery-sync.js --top 10 --days 5",
      cwd: __dirname,
      interpreter: "none",
      env_file: ".env",
      autorestart: false,
      cron_restart: "20 18 * * 1-5",
      timezone: "Asia/Kolkata",
    },
  ],
};
